# Generated by Django 4.2 on 2023-04-16 19:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('atuacao_profissional', '0001_initial'),
        ('formacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('endereco', models.CharField(max_length=150, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo_user', models.CharField(choices=[('P', 'Profissional'), ('F', 'Familiar de Autista')], default='F', max_length=2)),
                ('especialidade', models.ManyToManyField(to='atuacao_profissional.atuacao_profissional')),
                ('formacao', models.ManyToManyField(to='formacao.formacao')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
