# Generated by Django 4.2 on 2023-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='', upload_to='media/user'),
        ),
    ]
