# Generated by Django 4.2 on 2023-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('profissional', 'Profissional'), ('autista', 'Autista')], default='profissional', max_length=12),
        ),
    ]
