# Generated by Django 4.2 on 2023-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_nome_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
    ]
