# Generated by Django 4.2 on 2023-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('accounts', '0003_remove_usuario_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='forum',
            field=models.ManyToManyField(to='forum.forum'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
