# Generated by Django 4.2 on 2023-04-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos_academicos', '0001_initial'),
        ('accounts', '0004_usuario_forum_delete_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='especialidade',
            new_name='atuacao_profissional',
        ),
        migrations.AddField(
            model_name='usuario',
            name='trabalhos_academicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabalhos_academicos.trabalhos_academicos'),
        ),
    ]
