# Generated by Django 4.2 on 2023-04-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_especialidade_usuario_atuacao_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF:'),
        ),
    ]
