# Generated by Django 4.2 on 2023-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_mensagem_autor'),
        ('formacao', '0001_initial'),
        ('accounts', '0007_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='formacao',
            field=models.ManyToManyField(to='formacao.formacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sala',
            field=models.ManyToManyField(to='forum.sala'),
        ),
    ]
