# Generated by Django 4.2 on 2023-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usuario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sala',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='media/perfil'),
        ),
    ]
