# Generated by Django 4.2 on 2023-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_usuario_sala_alter_usuario_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('P', 'Profissional'), ('F', 'Familiar')], max_length=1),
        ),
    ]
