# Generated by Django 4.2 on 2023-07-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usuario_tipousuario'),
    ]

    operations = [
    ]
