# Generated by Django 4.2 on 2023-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='especializacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
