# Generated by Django 4.2 on 2023-04-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos_academicos',
            name='anexo',
            field=models.FileField(default='', upload_to='meusarquivos/'),
        ),
        migrations.AlterField(
            model_name='trabalhos_academicos',
            name='ano',
            field=models.DateField(verbose_name='Ano de Publicação'),
        ),
        migrations.AlterField(
            model_name='trabalhos_academicos',
            name='autores',
            field=models.CharField(max_length=100, verbose_name='Autor(es)'),
        ),
        migrations.AlterField(
            model_name='trabalhos_academicos',
            name='titulo_trabalho',
            field=models.CharField(max_length=150, verbose_name='Título do Trabalho'),
        ),
    ]
