# Generated by Django 4.2 on 2023-06-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhos_academicos',
            name='ano',
            field=models.IntegerField(verbose_name='Ano de Publicação'),
        ),
        migrations.AlterField(
            model_name='trabalhos_academicos',
            name='revista',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
