# Generated by Django 4.2 on 2023-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='mensagens',
            field=models.ManyToManyField(blank=True, to='forum.mensagem'),
        ),
    ]
