# Generated by Django 4.2 on 2023-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/forum'),
        ),
    ]
