# Generated by Django 4.2 on 2023-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='sala',
        ),
        migrations.AddField(
            model_name='sala',
            name='mensagens',
            field=models.ManyToManyField(blank=True, to='forum.mensagem'),
        ),
    ]
