# Generated by Django 4.2 on 2023-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_mensagem_sala_sala_mensagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='mensagens',
            field=models.ManyToManyField(blank=True, null=True, to='forum.mensagem'),
        ),
    ]
