# Generated by Django 4.2 on 2023-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_sala_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='sala',
        ),
        migrations.AddField(
            model_name='sala',
            name='mensagens',
            field=models.ManyToManyField(blank=True, to='forum.mensagem'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='forum/'),
        ),
    ]
