# Generated by Django 4.2 on 2023-05-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_mensagem_sala_sala_mensagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
