# Generated by Django 4.2 on 2023-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_sala_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
