# Generated by Django 4.2 on 2023-07-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_usuario_sala_alter_usuario_img'),
        ('forum', '0004_alter_mensagem_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='accounts.usuario'),
        ),
    ]
