# Generated by Django 4.2 on 2023-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_mensagem_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='anexo',
            field=models.ImageField(blank=True, null=True, upload_to='forum'),
        ),
    ]
