# Generated by Django 4.2 on 2023-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atuacao_Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150)),
                ('dia_hrs_atendimento', models.DateTimeField()),
                ('especialidade', models.CharField(choices=[('analista do comportamento', 'Analista do comportamento'), ('fonoaudiologo', 'Fonoaudiólogo'), ('psicopedagogo', 'Psicopedagogo'), ('terapeuta ocupacional', 'Terapeuta ocupacional'), ('fisioterapeutas', 'Fisioterapeutas'), ('musicoterapia', 'Musicoterapia'), ('acompanhante terapêutico', 'Acompanhante Terapêutico'), ('psicologo', 'Psicologo'), ('neurologista', 'Neurologista'), ('psiquiatra', 'Psiquiatra'), ('pediatra', 'Pediatra'), ('psicomotricista', 'Psicomotricista')], default='psicologo', max_length=25)),
            ],
        ),
    ]
