# Generated by Django 4.2 on 2023-05-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade_CHOICES', models.CharField(choices=[('analista do comportamento', 'Analista do comportamento'), ('fonoaudiologo', 'Fonoaudiólogo'), ('psicopedagogo', 'Psicopedagogo'), ('terapeuta ocupacional', 'Terapeuta ocupacional'), ('fisioterapeutas', 'Fisioterapeutas'), ('musicoterapia', 'Musicoterapia'), ('acompanhante terapêutico', 'Acompanhante Terapêutico'), ('psicologo', 'Psicologo'), ('neurologista', 'Neurologista'), ('psiquiatra', 'Psiquiatra'), ('pediatra', 'Pediatra'), ('psicomotricista', 'Psicomotricista')], max_length=50)),
                ('especialidade_add', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atuacao_Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(max_length=150)),
                ('dias_atendimento', models.DateField(blank=True, null=True)),
                ('horario_atendimento', models.TimeField(blank=True, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atuacao_profissional.especialidade')),
            ],
        ),
    ]
