# Generated by Django 4.2 on 2023-05-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade_add',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
