# Generated by Django 4.2 on 2023-04-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='atuacao_profissional',
            name='dia_hrs_atendimento',
        ),
        migrations.AddField(
            model_name='atuacao_profissional',
            name='dia',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='atuacao_profissional',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='especialidade',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.DO_NOTHING, to='atuacao_profissional.especialidade'),
        ),
    ]
