# Generated by Django 4.2 on 2023-04-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0002_especialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atuacao_profissional',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='atuacao_profissional',
            name='especialidade_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='atuacao_profissional.especialidade'),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='especialidade',
            field=models.CharField(choices=[('analista do comportamento', 'Analista do comportamento'), ('fonoaudiologo', 'Fonoaudiólogo'), ('psicopedagogo', 'Psicopedagogo'), ('terapeuta ocupacional', 'Terapeuta ocupacional'), ('fisioterapeutas', 'Fisioterapeutas'), ('musicoterapia', 'Musicoterapia'), ('acompanhante terapêutico', 'Acompanhante Terapêutico'), ('psicologo', 'Psicologo'), ('neurologista', 'Neurologista'), ('psiquiatra', 'Psiquiatra'), ('pediatra', 'Pediatra'), ('psicomotricista', 'Psicomotricista')], default='psicologo', max_length=50),
        ),
    ]
