# Generated by Django 4.2 on 2023-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0003_remove_atuacao_profissional_especialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atuacao_profissional',
            name='especialidade_user',
        ),
        migrations.AddField(
            model_name='atuacao_profissional',
            name='especialidade',
            field=models.CharField(choices=[('analista do comportamento', 'Analista do comportamento'), ('fonoaudiologo', 'Fonoaudiólogo'), ('psicopedagogo', 'Psicopedagogo'), ('terapeuta ocupacional', 'Terapeuta ocupacional'), ('fisioterapeutas', 'Fisioterapeutas'), ('musicoterapia', 'Musicoterapia'), ('acompanhante terapêutico', 'Acompanhante Terapêutico'), ('psicologo', 'Psicologo'), ('neurologista', 'Neurologista'), ('psiquiatra', 'Psiquiatra'), ('pediatra', 'Pediatra'), ('psicomotricista', 'Psicomotricista')], default='psicologo', max_length=25),
        ),
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='dia',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
    ]
