# Generated by Django 4.2 on 2023-04-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0004_remove_atuacao_profissional_especialidade_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='dia',
            field=models.DateField(blank=True, null=True, verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='horário'),
        ),
    ]
