# Generated by Django 4.2 on 2023-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0005_alter_atuacao_profissional_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atuacao_profissional',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
