# Generated by Django 4.2 on 2023-04-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atuacao_profissional', '0006_alter_atuacao_profissional_dia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atuacao_profissional',
            old_name='dia',
            new_name='dias_atendimento',
        ),
        migrations.RenameField(
            model_name='atuacao_profissional',
            old_name='hora',
            new_name='horario_atendimento',
        ),
        migrations.RenameField(
            model_name='atuacao_profissional',
            old_name='nome_empresa',
            new_name='nome_da_empresa',
        ),
    ]
